# --- File Paths ---
# Set these to your local paths
data_directory: "path/to/your/data/"
output_directory: "path/to/output/"

# --- Experiment Parameters ---
pretrain_flight: "30Oct24, 10Feb25"
overweight_flight: "30Oct24, 10Feb25"
overweight_factor: 1.8
validation_flight: "04Nov24, 12Feb25" # Flight to use for validation set

# --- Training Parameters ---
learning_rate: 0.001
weight_decay: 0.05
epochs: 80 # Increased epochs for more training with attention
optimizer: "AdamW"
scheduler: "ReduceLROnPlateau"
temporal_frames: 6
loss_type: "weighted_huber_mae" # Use weighted huber mae loss
loss_alpha: 0.8 # Not needed for simplified Huber loss
early_stopping_patience: 10 # Increased patience for longer training with attention
filter_type: "basic"
early_stopping_min_delta: 0.00025
huber_delta: 1.0
gamma: 1.5
under_weight: 1.0
loo: true
loo_epochs: 20
batch_size: 16
warmup_steps: 2000
hard_mining_k: 0.35
hard_mining_factor: 1.5
swath_slice: [40, 480]
hpc_mode: false
use_conformal_prediction: true
prediction_clip_range: [0.1, 2.0] # Clip predictions to a range of 0.1km to 2km
conformal_confidence: 0.9
#angles_mode: 'sza_only'
augment: true
nclude_validation_in_train: true

# --- Model Architecture ---
architecture:
  name: "transformer" # Options: "transformer", "gnn", "ssm"

# --- Flight Information ---
flights:
  - name: "10Feb25"
    iFileName: "10Feb25/GLOVE2025_IRAI_L1B_Rev-_20250210.h5"
    cFileName: "10Feb25/CPL_L2_V1-02_01kmLay_259015_10feb25.hdf5"
    nFileName: "10Feb25/CRS_20250210_nav.hdf"
  - name: "30Oct24"
    iFileName: "30Oct24/WHYMSIE2024_IRAI_L1B_Rev-_20241030.h5"
    cFileName: "30Oct24/CPL_L2_V1-02_01kmLay_259006_30oct24.hdf5"
    nFileName: "30Oct24/CRS_20241030_nav.hdf"
  - name: "04Nov24"
    iFileName: "04Nov24/WHYMSIE2024_IRAI_L1B_Rev-_20241104.h5"
    cFileName: "04Nov24/CPL_L2_V1-02_01kmLay_259008_04nov24.hdf5"
    nFileName: "04Nov24/CRS_20241104_nav.hdf"
  - name: "23Oct24"
    iFileName: "23Oct24/WHYMSIE2024_IRAI_L1B_Rev-_20241023.h5"
    cFileName: "23Oct24/CPL_L2_V1-02_01kmLay_259004_23oct24.hdf5"
    nFileName: "23Oct24/CRS_20241023_nav.hdf"
  - name: "18Feb25"
    iFileName: "18Feb25/GLOVE2025_IRAI_L1B_Rev-_20250218.h5"
    cFileName: "18Feb25/CPL_L2_V1-02_01kmLay_259017_18feb25.hdf5"
    nFileName: "18Feb25/CRS_20250218_nav.hdf"
  - name: "12Feb25"
    iFileName: "12Feb25/GLOVE2025_IRAI_L1B_Rev-_20250212.h5"
    cFileName: "12Feb25/CPL_L2_V1-02_01kmLay_259016_12feb25.hdf5"
    nFileName: "12Feb25/CRS_20250212_nav.hdf"
