# --- PHASE 2 EXPERIMENT: SIMPLE CNN BASELINE ---
# This config uses a simple CNN architecture without attention mechanisms
# to test if the complex transformer architecture is causing the training issues.
#
# Key changes from phase_1_variance_fix.yaml:
#   - architecture: "cnn" (simple CNN, no attention/transformer)
#   - Disabled spatial and temporal attention
#   - Disabled multiscale temporal
#   - Same variance loss settings (variance_lambda=0.5)

# --- File Paths ---
data_directory: "/content/drive/MyDrive/CloudML/data/"
output_directory: "/content/drive/MyDrive/CloudML/plots/"
models_directory: "/content/drive/MyDrive/CloudML/models/trained/"
log_dir: "/content/drive/MyDrive/CloudML/logs/"

# --- Experiment Parameters ---
pretrain_flight: "30Oct24"
overweight_flight: "30Oct24"
overweight_factor: 1.0
validation_flight: "12Feb25"

# --- Training Parameters ---
learning_rate: 0.0005
weight_decay: 0.04
epochs: 10 # SHORT RUN FOR VALIDATION
optimizer: "AdamW"
scheduler: "ReduceLROnPlateau"
temporal_frames: 3
loss_type: "huber"
loss_alpha: 0.5
variance_lambda: 0.5 # Keep variance loss to prevent collapse
min_variance_ratio: 0.1 # SAFETY NET - STOP IF VARIANCE < 10%
early_stopping_patience: 5 # Shorter patience for 10-epoch run
filter_type: "basic"
early_stopping_min_delta: 0.0005
huber_delta: 1.0
gamma: 1.5
under_weight: 1.0
loo: false
loo_epochs: 30
batch_size: 20
warmup_steps: 500
hard_mining_k: 0.35
hard_mining_factor: 1.5
swath_slice: [40, 480]
hpc_mode: true

# --- Memory & Performance Optimization ---
memory_optimized: false
gradient_checkpointing: true
torch_compile: true
torch_compile_mode: "default"

# --- Data Loading Optimization ---
num_workers: 2
pin_memory: true
prefetch_factor: 3

# --- Model Architecture ---
use_spatial_attention: false # PHASE 2: Disable all attention
use_temporal_attention: false # PHASE 2: Disable all attention
use_multiscale_temporal: false # PHASE 2: Disable multiscale
attention_heads: 4 # Unused when attention disabled
flat_field_correction: true
clahe_clip_limit: 0.01
zscore_normalize: true
augment: true
angles_mode: "both"

architecture:
  name: "cnn" # PHASE 2: Use simple CNN instead of transformer

# --- Flight Information ---
flights:
  - name: "10Feb25"
    iFileName: "10Feb25/GLOVE2025_IRAI_L1B_Rev-_20250210.h5"
    cFileName: "10Feb25/CPL_L2_V1-02_01kmLay_259015_10feb25.hdf5"
    nFileName: "10Feb25/CRS_20250210_nav.hdf"
  - name: "30Oct24"
    iFileName: "30Oct24/WHYMSIE2024_IRAI_L1B_Rev-_20241030.h5"
    cFileName: "30Oct24/CPL_L2_V1-02_01kmLay_259006_30oct24.hdf5"
    nFileName: "30Oct24/CRS_20241030_nav.hdf"
  - name: "04Nov24"
    iFileName: "04Nov24/WHYMSIE2024_IRAI_L1B_Rev-_20241104.h5"
    cFileName: "04Nov24/CPL_L2_V1-02_01kmLay_259008_04nov24.hdf5"
    nFileName: "04Nov24/CRS_20241104_nav.hdf"
  - name: "23Oct24"
    iFileName: "23Oct24/WHYMSIE2024_IRAI_L1B_Rev-_20241023.h5"
    cFileName: "23Oct24/CPL_L2_V1-02_01kmLay_259004_23oct24.hdf5"
    nFileName: "23Oct24/CRS_20241023_nav.hdf"
  - name: "18Feb25"
    iFileName: "18Feb25/GLOVE2025_IRAI_L1B_Rev-_20250218.h5"
    cFileName: "18Feb25/CPL_L2_V1-02_01kmLay_259017_18feb25.hdf5"
    nFileName: "18Feb25/CRS_20250218_nav.hdf"
  - name: "12Feb25"
    iFileName: "12Feb25/GLOVE2025_IRAI_L1B_Rev-_20250212.h5"
    cFileName: "12Feb25/CPL_L2_V1-02_01kmLay_259016_12feb25.hdf5"
    nFileName: "12Feb25/CRS_20250212_nav.hdf"

# --- Self-Supervised Pre-training ---
pretraining:
  enabled: false
  epochs: 20
  learning_rate: 0.0001
  batch_size: 8
  save_checkpoints: true
  checkpoint_dir: "/content/drive/MyDrive/CloudML/models/pretrained/"
# --- PHASE 2 EXPERIMENT NOTES ---
# OBJECTIVE: Test if complex architecture is causing training failure
#
# PHASE 1 RESULTS:
#   - Variance ratio: Good (88-111%)
#   - R²: Still negative (-0.89 to -1.16)
#   - Loss: Still too high (600-900)
#   - Predictions: Wrong scale, some negative values
#
# HYPOTHESIS:
#   - Complex transformer/attention architecture is not learning
#   - Simpler CNN might learn the basic relationship first
#
# THIS EXPERIMENT:
#   - Use SimpleCNNModel (no attention, no transformer)
#   - Same variance loss (variance_lambda=0.5)
#   - Same 10 epoch short run
#
# SUCCESS CRITERIA:
#   - Loss should drop significantly (< 2.0)
#   - R² should be positive and increasing
#   - Predictions should be in valid range (0.1-2.0 km)
#
# IF SUCCESSFUL:
#   - Simple CNN works! Gradually add complexity back
#
# IF UNSUCCESSFUL:
#   - Issue is deeper (data pipeline, loss function, or data quality)
